dev module2-task1
htmlacademy-ecmascript/1808687-cinemaddict-15 pull request #4
Opened 2021-08-05 18:44 UTC by Akame320

2021-08-06 12:52 UTC, dtsaryov requested changes

2021-08-06 12:52 UTC, dtsaryov commented on markup/popup.html
> -          </li>
Верни, пожалуйста, где лежало

2021-08-06 12:52 UTC, dtsaryov commented on src/view/popup/film-details-row.js
> +);
Не надо отдельный шаблон для этого

2021-08-06 12:52 UTC, dtsaryov commented on src/view/popup/comment-row.js
> +export const createCommentRow = (data) => (
createCommentTemplate, никаких row

2021-08-06 12:52 UTC, dtsaryov commented on src/view/popup/comment-row.js
> +export const createCommentRow = (data) => (
ну и comment, а не data

не надо использовать data, если можно использовать более конкретное имя

2021-08-06 12:52 UTC, dtsaryov commented on src/view/popup/comment-button-delete.js
> +);
Не нужен этот шаблон

2021-08-06 12:52 UTC, dtsaryov commented on src/view/popup/comment-button-delete.js
> +);
Как минимум потому, что тут нет никаких изменяемых данных

2021-08-06 12:52 UTC, dtsaryov commented on src/view/films/films-show-more.js
> +export const createFilmsShowMore = () => {
createShowMoreButtonTemplate

2021-08-06 12:52 UTC, dtsaryov commented on src/view/film-card/film-card.js
> +export const createFilmCart = (data) => {
ну createFilmCard же

2021-08-06 12:52 UTC, dtsaryov commented on src/view/film-card/film-card.js
> +    return description >= 140 ? description.join('') : description.join('').substr(0, 140) + '&hellip;';
Б31. В коде не используются «магические значения», под каждое из них заведена отдельная переменная, названная как константа.

2021-08-06 12:52 UTC, dtsaryov commented on src/view/film-card/film-card.js
> +  const getFormatDescription = () => {
truncateDescription

2021-08-06 12:52 UTC, dtsaryov commented on src/view/film-card/film-card.js
> +    return description >= 140 ? description.join('') : description.join('').substr(0, 140) + '&hellip;';
И откуда join'ы взялись?

2021-08-06 12:52 UTC, dtsaryov commented on src/view/films/films-list.js
> +        ${createFilmsShowMore()}
Эта кнопка должна рендериться в main

2021-08-06 12:52 UTC, dtsaryov commented on src/main.js
> +import {createComment, createFilm, mock, setIdForFilm} from "./mocks/films-data";
Тонна ошибок ESLint

2021-08-06 12:52 UTC, dtsaryov commented on src/main.js
> +const films = new Array(13).fill(null).map(() => createFilm());
fill(null).map(createFilm)

2021-08-06 12:52 UTC, dtsaryov commented on src/mocks/films-data.js
> +const getRandomComments = () => {
Тут ты создаешь один коммент, а имя функции не соответствует действительности

2021-08-06 12:52 UTC, dtsaryov commented on src/mocks/films-data.js
> +const getRandomComments = () => {
Ну и:

```JS
const foo = () => ({
  name: 'John Doe'
});
```

2021-08-06 12:52 UTC, dtsaryov commented on src/mocks/films-data.js
> +  }
Зачем объект?

2021-08-06 14:41 UTC, Akame320 commented on src/view/film-card/film-card.js
> +    return description >= 140 ? description.join('') : description.join('').substr(0, 140) + '&hellip;';
Переменная "description" - хранит ссылку на массив. Мне надо получить переменную типа string. Для этого использую join('');

2021-08-06 14:51 UTC, Akame320 commented on src/view/popup/comment-button-delete.js
> +);
Я хотел сделать ее компонентом, а не шаблоном. Эта кнопка нужна для удаления комментария. Для этого нам надо будет писать код. Этот код я планирую писать прям в этом же файле (src/view/popup/comment-button-delete.js). Вроде логично. Поправь если думаю не так

2021-08-06 14:58 UTC, Akame320 commented on src/view/popup/film-details-row.js
> +);
Почему?

2021-08-06 21:52 UTC, dtsaryov commented on src/view/popup/film-details-row.js
> +);
Во-перых, потому что это не самодостаточный кусок.

Во-вторых, он используется только в одном месте.

Если и хочешь переиспользовать, то оставь эту функцию в модуле с основным шаблоном

2021-08-06 21:53 UTC, dtsaryov commented on src/view/popup/comment-button-delete.js
> +);
Нет, так не надо делать. Бизнес-логика в компонентах никогда не пишется

2021-08-06 21:54 UTC, dtsaryov commented on src/view/film-card/film-card.js
> +    return description >= 140 ? description.join('') : description.join('').substr(0, 140) + '&hellip;';
С чего там вдруг массив?

2021-08-07 13:27 UTC, dtsaryov requested changes

2021-08-07 13:27 UTC, dtsaryov commented on src/main.js
> +};
Ну и, кстати, пузырёк тут не нужен - это делается за один проход по массиву (`O(N)` вместо `O(N^2)`):

https://jsfiddle.net/x3eu2sr7/1/

2021-08-07 13:27 UTC, dtsaryov commented on markup/popup.html
> -          </li>
Так и не вернул

2021-08-07 13:27 UTC, dtsaryov commented on src/mocks/films-data.js
> +const commentsTexts = ['Interesting setting and a good cast', 'Booooooooooring', 'Very very old. Meh', 'Almost two hours? Seriously?'];
Б5. Названия констант (постоянных значений) написаны прописными (заглавными) буквами.

2021-08-07 13:27 UTC, dtsaryov commented on src/main.js
> +for (let i = 0; i < 5; i++){
Б31. В коде не используются «магические значения», под каждое из них заведена отдельная переменная, названная как константа.

2021-08-07 13:27 UTC, dtsaryov commented on src/main.js
> +const comments = new Array(5).fill(null).map(createComment);
Б31. В коде не используются «магические значения», под каждое из них заведена отдельная переменная, названная как константа.

2021-08-07 13:27 UTC, dtsaryov commented on src/main.js
> +let showsFilmsCartInMainList = 5;
Б31. В коде не используются «магические значения», под каждое из них заведена отдельная переменная, названная как константа.

2021-08-07 13:27 UTC, dtsaryov commented on src/main.js
> +const showMoreFilmsCart = () => {
Я скоро клавиатуру сотру исправлять тебя - card.

cart - это корзина

2021-08-07 13:27 UTC, dtsaryov commented on src/main.js
> +    showsFilmsCartInMainList += 5;
Б31. В коде не используются «магические значения», под каждое из них заведена отдельная переменная, названная как константа.

2021-08-07 13:27 UTC, dtsaryov commented on src/main.js
> +    while(showsFilmsCartInMainList < showsFilmsCartInMainList + 5 && films[i]){
Б31. В коде не используются «магические значения», под каждое из них заведена отдельная переменная, названная как константа.

2021-08-07 13:27 UTC, dtsaryov commented on src/main.js
> +document.querySelector('.films-list__show-more').addEventListener('click', showMoreFilmsCart);
Эту кнопку, кстати, ручками надо отрисовывать

2021-08-07 13:27 UTC, dtsaryov commented on src/view/film-card/film-card.js
> +  };
1. Не надо объявлять функции внутри функций без надобности
2. Описание надо передавать через аргументы
3. Б31. В коде не используются «магические значения», под каждое из них заведена отдельная переменная, названная как константа.

2021-08-07 13:27 UTC, dtsaryov commented on src/view/popup/popup.js
> +export const createPopup = (dataFilm, dataComments) => (
не используй слово data

2021-08-07 13:27 UTC, dtsaryov commented on src/view/film-card/film-card.js
> +      <span class="film-card__genre">${data.categories[0]}</span>
genres, а не categories

2021-08-07 13:27 UTC, dtsaryov commented on src/mocks/films-data.js
> +  const film = {
Структура не соответствует описанной в ТЗ:

https://up.htmlacademy.ru/ecmascript/15/project/cinemaddict#resource

2021-08-07 13:27 UTC, dtsaryov commented on src/mocks/films-data.js
> +  const randomComment = {
Структура не соответствует описанной в ТЗ:

https://up.htmlacademy.ru/ecmascript/15/project/cinemaddict#resource

2021-08-07 13:38 UTC, dtsaryov commented on src/main.js
> +};
^ нашел тут ошибку, правлю

2021-08-07 15:59 UTC, dtsaryov commented on src/main.js
> +};
https://jsfiddle.net/t0Lquay6/

2021-08-07 18:04 UTC, dtsaryov commented on src/view/film-card/film-card.js
> +  return outDescription >= MAX_CHARS_FOR_TRUNCATE ? outDescription : `${outDescription.substr(0, MAX_CHARS_DESCRIPTION - 1)} &hellip;`;
Ты здесь строку с числом сравниваешь.

И можно обойтись без доп переменной

2021-08-07 18:04 UTC, merged